version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    depends_on:
      - backend
    environment:
      - PORT=$FRONTEND_LOCAL_PORT
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default
    command: npm run dev -- --host


  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    depends_on:
      - db
    networks:
      - default
    command: npm run start:dev

  db:
    image: mysql:latest
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  db-data:
